### ISSUE TITLE
Access rights

### ISSUE THREAD

**Issue by danhammer** [DS-100/fa22#3]
@fperez I am ready to submit a PR for my lecture on Thursday.  I started a new branch that should be _super_ easy to merge, called `lecture/lec22`.  I can't push to this repo.  Should I fork the repo and submit a PR from the fork?  Or can I have write access to this repo? 
```
(base) comprock:fa22 danhammer$ git push origin lecture/lec22
ERROR: Permission to DS-100/fa22.git denied to danhammer.
```

**Comment by fperez** [comment]
Thanks @danhammer! I just sent you an invite to the staff team for the term, which has write privileges. Go for it, and feel free to tag me (I suggest you make a PR that you can merge yourself, but that way it's easier to see your commits all together in one bunch).
